spring:
  application:
    name: paulo-motors-api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      ssl-mode: require
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME:paullomagio@gmail.com}
    password: ${MAIL_PASSWORD:qsmsyeqpjdtxwfrt}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
        transport:
          protocol: smtps

api:
  security:
    token:
      secret: ${JWT_SECRET:minha-chave-secreta-muito-segura-123}